<header>
    <h1>Exercice routing</h1>
    <nav>
        <ul>
            <li>
                <a href="templates/partials/homepage.phtml">Accueil</a>
            </li>
            <li>
                <a href="templates/partials/about.phtml">À propos</a>
            </li>
            <li>
                <a href="templates/partials/contact.phtml">Contact</a>
            </li>
        </ul>
    </nav>
</header>