<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Créer un utilisateur</title>
</head>
<body>
    <h1>Créer un nouvel utilisateur</h1>
    <form action="index.php?route=check_create_user" method="post">
        <label for="email">Email :</label><br>
        <input type="email" id="email" name="email"><br><br>

        <label for="first_name">Prénom :</label><br>
        <input type="text" id="first_name" name="first_name"><br><br>

        <label for="last_name">Nom :</label><br>
        <input type="text" id="last_name" name="last_name"><br><br>

        <button type="submit">Créer</button>
    </form>
    <?php
    
    ?>
</body>
</html>