<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD MVC </title>
    <link rel="stylesheet" href="assets/styles/style.css">
    
</head>
<body>
    <header>
        <h1>CRUD MVC Application</h1>
        <nav>
            <ul>
                <li><a href="index.php">Accueil</a></li>
                <li><a href="index.php?route=create_user">Créer un utilisateur</a></li>
            </ul>
        </nav>
    </header>
    <?php require "templates/users/$route.phtml" ?>
    
</body>
</html>